
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    rest:
      uris: localhost:1001,localhost:1002,localhost:1003
      username: my-application

#      server.port=7777
#      server.servlet.path =/es
#      # elasticsearch集群名称，默认的是elasticsearch
#      spring.data.elasticsearch.cluster-name=wtyy-es
#      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
#      spring.data.elasticsearch.cluster-nodes=xxx.xx.xxx.32:9300,xxx.xx.xxx.126:9300,xxx.xx.xxx.151:9300
#
#      #是否开启本地存储
#      spring.data.elasticsearch.repositories.enable=true
